DROP TABLE demo

CREATE TABLE demo(
	P_ID SERIAL PRIMARY KEY,
	FIRST_NAME VARCHAR(255) NOT NULL,
	DEPARTMENT VARCHAR(255),
	AGE INT
);

INSERT INTO demo(FIRST_NAME, DEPARTMENT, AGE) VALUES 
('AJWAD', 'BSCS', 21),
('AHMAD', 'BSSE', 20),
('ALI', 'BSAI', 22),
('SAQIB', 'BSCS', 24),
('IMRAN', 'BSSC', 21);

TRUNCATE demo -- EMPTY DATA IN TABLE

SELECT *FROM demo

SELECT FIRST_NAME, AGE FROM demo WHERE DEPARTMENT = 'BSCS'

SELECT FIRST_NAME, AGE FROM demo WHERE FIRST_NAME LIKE 'A%' -- SELECT NAME START WITH A and % mean WHATEVER THEN

SELECT FIRST_NAME, AGE FROM demo WHERE DEPARTMENT IN ('BSCS', 'BSSE')

SELECT FIRST_NAME, AGE FROM demo WHERE AGE BETWEEN 20 AND 22

SELECT DISTINCT DEPARTMENT FROM demo -- Remove Duplicate Values

UPDATE DEMO SET DEPARTMENT ='ADC' WHERE P_ID = 13

DELETE FROM DEMO WHERE P_ID = 15

SELECT *FROM DEMO

SELECT DEPARTMENT, AGE FROM DEMO ORDER BY DEPARTMENT, AGE DESC

SELECT DEPARTMENT, MAX(AGE), COUNT(*)AS TOTAL  FROM DEMO GROUP BY DEPARTMENT, AGE HAVING COUNT(*) > 1

SELECT * FROM DEMO LIMIT 3

SELECT * FROM DEMO ORDER BY AGE DESC LIMIT 3

ALTER TABLE DEMO ADD COLUMN ROLLNO INT
ALTER TABLE DEMO DROP COLUMN AGE

DROP TABLE COURSE

CREATE TABLE COURSE(
	C_ID INT,
	COURSE_NAME VARCHAR(250),
	CREDIT_HOUR INT CHECK (CREDIT_HOUR >= 1),
	CONSTRAINT FK_STUDENT_NAME FOREIGN KEY (C_ID) REFERENCES DEMO(P_ID)
);

INSERT INTO COURSE VALUES
(11,'DAA',3),
(12,'TOA',2),
(14,'SE',3) ,
(13,'OS',1);

SELECT * FROM demo

TRUNCATE COURSE

SELECT * FROM DEMO, COURSE WHERE DEMO.P_ID = COURSE.C_ID





